#!/bin/bash
set -e
set -x
export LC_ALL=C

if [ "$build_dir" = "" ]; then
    build_dir="."
fi
img="$1"
if [ "$img" = "" ]; then
    img="$build_dir/img"
fi

kvm -drive file=$img,format=raw -boot c -m 1024 -curses -net user,hostfwd=tcp::8022-:22 -net nic,model=e1000,macaddr=52:54:00:12:36:03

