#!/bin/bash
set -e
set -x
export LC_ALL=C

echo hostname-not-set | sudo tee fs/snapshot/0/etc/hostname
echo -e "auto lo\niface lo inet loopback\n\nauto eth0\niface eth0 inet dhcp" | sudo tee fs/snapshot/0/etc/network/interfaces
sudo mkdir -p fs/snapshot/0/etc/snapshot
echo "initial snapshot created on `date` at `hostname`" | sudo tee fs/snapshot/0/etc/snapshot/info
sudo mkdir -p fs/snapshot/0/root/.ssh
sudo cp ~/.ssh/id_dsa.pub fs/snapshot/0/root/.ssh/authorized_keys

sudo cp scripts/modules fs/snapshot/0/etc/initramfs-tools
sudo cp scripts/local-top fs/snapshot/0/etc/initramfs-tools/scripts/local-top/ramroot
sudo cp scripts/local-premount fs/snapshot/0/etc/initramfs-tools/scripts/local-premount/ramroot
sudo cp scripts/local-bottom fs/snapshot/0/etc/initramfs-tools/scripts/local-bottom/ramroot
sudo chroot fs/snapshot/0 update-initramfs -k all -c -t

sudo install scripts/ramroot-{aptgludge,snapshot} fs/snapshot/0/usr/local/bin

sudo mkdir -p fs/snapshot/0/boot/grub
echo y | sudo chroot fs/snapshot/0 update-grub
sudo sed -i s@/boot@/snapshot/0/boot@ fs/snapshot/0/boot/grub/menu.lst
sudo sed -i '/^kernel/s@ro $@ro snapshot=0 @' fs/snapshot/0/boot/grub/menu.lst
