#!/bin/bash
set -e
set -x
export LC_ALL=C

echo hostname-not-set | sudo tee fs/snapshot/0/etc/hostname
echo -e "auto lo\niface lo inet loopback\n\nauto eth0\niface eth0 inet dhcp" | sudo tee fs/snapshot/0/etc/network/interfaces
sudo mkdir -p fs/snapshot/0/etc/ramroot
echo "#0 `date -u +"%Y-%m-%d %H:%M"` initial snapshot" | sudo tee fs/snapshot/0/etc/ramroot/grub-title
sudo mkdir -p fs/snapshot/0/root/.ssh
sudo cp ~/.ssh/id_dsa.pub fs/snapshot/0/root/.ssh/authorized_keys
echo "retry 3600;" | sudo tee -a fs/snapshot/0/etc/dhclient.conf

sudo cp scripts/modules fs/snapshot/0/etc/initramfs-tools
sudo install scripts/local-top fs/snapshot/0/etc/initramfs-tools/scripts/local-top/ramroot
sudo install scripts/local-premount fs/snapshot/0/etc/initramfs-tools/scripts/local-premount/ramroot
sudo install scripts/local-bottom fs/snapshot/0/etc/initramfs-tools/scripts/local-bottom/ramroot
sudo install scripts/hooks fs/snapshot/0/etc/initramfs-tools/hooks/ramroot
sudo chroot fs/snapshot/0 update-initramfs -k all -c -t

sudo install scripts/ramroot-{aptkludge,snapshot,update-grub,admin} fs/snapshot/0/usr/local/bin
