#!/bin/bash
set -e
set -x
export LC_ALL=C

if [ -e img ]; then rm -f img; fi
if [ -d mnt ]; then rmdir mnt; fi
mkdir mnt
# 480*1024*1024/(512*63*255) = 61.2
dd if=/dev/zero of=img bs=1M count=0 seek=480
set +e
/sbin/fdisk -C 61 -H 255 -S 63 img <<EOF
n
p
1
1
61
a
1
w
q
EOF
set -e

if [ ! -e /dev/loop0 ]; then
    sudo modprobe loop
fi
loopdev="`sudo losetup -f`"
sudo losetup -o 32256 "${loopdev}" img
# (61-1)*255*63*512/4096 = 120487
sudo mkfs -t ext2 -b 4096 "${loopdev}" 120487
ramroot_uuid="`uuidgen | sed 's@^........-....-....@962d307f-8f1f-4301@'`"
sudo tune2fs -U $ramroot_uuid "${loopdev}"
sudo losetup -d "${loopdev}"

sudo mkdir -p fs/snapshot/0/boot/grub
echo y | sudo chroot fs/snapshot/0 update-grub

sudo mount img mnt -oloop,offset=32256
sudo cp -a fs/snapshot mnt
sudo mkdir -p mnt/boot/grub
if [ -d fs/snapshot/0/usr/lib/grub/i386-pc ]; then
    sudo cp fs/snapshot/0/usr/lib/grub/i386-pc/{stage1,e2fs_stage1_5,stage2} mnt/boot/grub
else
    sudo cp fs/snapshot/0/usr/lib/grub/x86_64-pc/{stage1,e2fs_stage1_5,stage2} mnt/boot/grub
fi    
sudo umount mnt

grub <<EOF
device (hd0) img
geometry (hd0) 61 255 63
root (hd0,0)
setup (hd0)
quit
EOF

sudo mount img mnt -oloop,offset=32256
sudo sh -c "ramroot_build=1 ramroot=mnt boot_uuid=$ramroot_uuid mnt/snapshot/0/usr/local/bin/ramroot-update-grub 0"
sudo umount mnt
rmdir mnt
