#!/bin/bash
set -e
set -x
export LC_ALL=C

if [ "$build_dir" = "" ]; then
    build_dir="."
fi
sudo chroot $build_dir/fs/snapshot/0 apt-get clean
sudo rm $build_dir/fs/snapshot/0/var/lib/apt/lists/*Packages
sudo rm -fr $build_dir/fs/snapshot/0/var/cache/apt
sudo mkdir $build_dir/fs/snapshot/0/var/cache/apt
sudo rm -fr $build_dir/fs/snapshot/0/usr/share/locale
sudo mkdir $build_dir/fs/snapshot/0/usr/share/locale
sudo rm -fr $build_dir/fs/snapshot/0/usr/share/doc
sudo mkdir $build_dir/fs/snapshot/0/usr/share/doc
sudo rm -fr $build_dir/fs/snapshot/0/usr/share/man/??
sudo rm -fr $build_dir/fs/snapshot/0/usr/share/man/??_*
sudo rm -fr $build_dir/fs/snapshot/0/lib/modules/*/kernel/{sound,drivers/media,drivers/isdn,drivers/video}
