#!/bin/sh
case "$1" in
    prereqs)
	echo ""
	exit 0
	;;
esac
echo "ramroot: local-top"
set -x
echo > /conf/param.conf
for x in $(cat /proc/cmdline); do
    case $x in
	ramroot_*=*)
	    echo "$x" >> /conf/param.conf
	    ;;
    esac
done
echo ROOT=/dev/null >> /conf/param.conf
#/bin/sh
