#!/bin/sh
case "$1" in
    prereqs)
	echo ""
	exit 0
	;;
esac
echo "ramroot: local-bottom"
set -x
mkdir /fs
modprobe ext2 # for amd64 (x86 has CONFIG_EXT2_FS=y)
while ! mount -n -oro /dev/disk/by-uuid/${ramroot_uuid} /fs; do
    ls -l /dev/disk/by-uuid
    echo "== Waiting for ${ramroot_uuid}"
    sleep 2
done
for i in /fs/snapshot/${ramroot_snapshot}/*; do
    cp -a $i ${rootmnt}
done
boot_uuid="`(cd /dev/disk/by-uuid; echo $ramroot_uuid)`"
echo "boot_uuid=${root_uuid}" > ${rootmnt}/etc/ramroot/boot-info
echo "boot_snapshot=${ramroot_snapshot}" >> ${rootmnt}/etc/ramroot/boot-info
echo "boot_uptime=`cut -d' ' -f1 /proc/uptime`" >> ${rootmnt}/etc/ramroot/boot-info
umount /fs
rmdir /fs
#/bin/sh
