#!/bin/sh
case "$1" in
    prereqs)
	echo ""
	exit 0
	;;
esac
echo "ramroot: local-top"
set -x
echo > /conf/param.conf
# defaults
echo "export ramroot_uuid=962d307f-8f1f-4301*" >> /conf/param.conf
echo "export ramroot_snapshot=0" >> /conf/param.conf
echo "export ramroot_fs=jffs2" >> /conf/param.conf
echo "export ramroot_fs_size=90000" >> /conf/param.conf
for x in $(cat /proc/cmdline); do
    case $x in
	ramroot_*=*)
	    echo "export $x" >> /conf/param.conf
	    ;;
    esac
done
echo ROOT=/dev/null >> /conf/param.conf
if [ "$ramroot_watchdog" != "" ]; then
    rmmod softdog
    modprobe softdog soft_margin=$ramroot_watchdog
    mknod /dev/watchdog c 10 130
    echo -n S > /dev/watchdog
fi
#/bin/sh
