#!/bin/sh
case "$1" in
    prereqs)
	echo ""
	exit 0
	;;
esac
echo "ramroot: local-premount"
set -x
echo > /conf/param.conf
if [ "$ramroot_fs" = "jffs2" ]; then
    echo FSTYPE=jffs2 > /conf/param.conf
    echo ROOTFLAGS="" >> /conf/param.conf
    echo ROOT=/dev/mtdblock0 >> /conf/param.conf
    echo readonly=n >> /conf/param.conf
    rmmod mtdram
    modprobe mtdram total_size=$ramroot_fs_size erase_size=128
    modprobe mtdblock
fi
if [ "$ramroot_fs" = "tmpfs" ]; then
    size=`expr $ramroot_fs_size '*' 1024`
    echo FSTYPE=tmpfs > /conf/param.conf
    echo ROOTFLAGS=-osize=$size >> /conf/param.conf
    echo ROOT=none >> /conf/param.conf
    echo readonly=n >> /conf/param.conf
fi
if [ "$ramroot_fs" = "fusecompress" ]; then
    modprobe fuse
    mkdir /tmpfs
    mem="`free | grep Mem: | awk '{ print $2 }'`"
    size=`expr $mem '*' 1024`
    mount none /tmpfs -t tmpfs -osize=$size
    fusecompress /tmpfs /root
    echo FSTYPE=dummy > /conf/param.conf
    echo ROOTFLAGS= >> /conf/param.conf
    echo ROOT=none >> /conf/param.conf
    echo readonly=n >> /conf/param.conf
fi
if [ "$ramroot_fs" = "solid" ]; then
    storage="/dev/disk/by-uuid/$ramroot_fs_uuid"
    while [ ! -e $storage ]; do
	sleep 2;
    done
    mke2fs -F $storage
    tune2fs -f -U $ramroot_fs_uuid $storage
    echo FSTYPE=ext2 > /conf/param.conf
    echo ROOTFLAGS= >> /conf/param.conf
    echo ROOT=$storage >> /conf/param.conf
    echo readonly=n >> /conf/param.conf
fi
#/bin/sh
