#!/bin/sh
case "$1" in
    prereqs)
	echo ""
	exit 0
	;;
esac
echo "ramroot: local-top"
set -x
echo > /conf/param.conf
# defaults
echo "ramroot_uuid=962d307f-8f1f-4301*"
echo "ramroot_snapshot=0"
echo "ramroot_fs=jffs2"
echo "ramroot_fs_size=90000"
for x in $(cat /proc/cmdline); do
    case $x in
	ramroot_*=*)
	    echo "$x" >> /conf/param.conf
	    ;;
    esac
done
echo ROOT=/dev/null >> /conf/param.conf
#/bin/sh
