#!/bin/sh
case "$1" in
    prereqs)
	echo ""
	exit 0
	;;
esac
echo "ramroot: local-premount"
set -x
echo > /conf/param.conf
if [ "$ramroot_fs" = "jffs2" ]; then
    echo FSTYPE=jffs2 > /conf/param.conf
    echo ROOTFLAGS="" >> /conf/param.conf
    echo ROOT=/dev/mtdblock0 >> /conf/param.conf
    echo readonly=n >> /conf/param.conf
    rmmod mtdram
    modprobe mtdram total_size=$ramroot_fs_size erase_size=128
    modprobe mtdblock
fi
if [ "$ramroot_fs" = "tmpfs" ]; then
    size=`expr $ramroot_fs_size '*' 1024`
    echo FSTYPE=tmpfs > /conf/param.conf
    echo ROOTFLAGS=-osize=$size >> /conf/param.conf
    echo ROOT=none >> /conf/param.conf
    echo readonly=n >> /conf/param.conf
fi
if [ "$ramroot_fs" = "fusecompress" ]; then
    modprobe fuse
    mkdir /tmpfs
    mem="`free | grep Mem: | awk '{ print $2 }'`"
    size=`expr $mem '*' 1024`
    mount none /tmpfs -t tmpfs -osize=$size
    fusecompress /tmpfs /root
    echo FSTYPE=dummy > /conf/param.conf
    echo ROOTFLAGS= >> /conf/param.conf
    echo ROOT=none >> /conf/param.conf
    echo readonly=n >> /conf/param.conf
fi
if [ "$ramroot_fs" = "swap" ]; then
    d="/dev/disk/by-uuid/$ramroot_fs_uuid"
    while [ ! -e $d ]; do
	ls -l /dev/disk/by-uuid
	echo "waiting for ramroot_fs"
	sleep 2
    done

    if [ `/lib/udev/vol_id -t $d` != "swap" ]; then
	echo "ramroot_fs_uuid does not point to swap!"
	/bin/sh
    fi

    losetup -o 4096 /dev/loop7 $d
    mke2fs /dev/loop7
    echo FSTYPE=ext2 > /conf/param.conf
    echo ROOTFLAGS= >> /conf/param.conf
    echo ROOT=/dev/loop7 >> /conf/param.conf
    echo readonly=n >> /conf/param.conf
fi
#/bin/sh
