#!/bin/sh
if [ "$1" = "--help" -o "$1" = "-h" ]; then
    (
        cat <<EOF
usage: ramroot-admin [--help] COMMAND

Run COMMAND so that the ramroot environment variable points to the
read-only mounted ramroot snapshot directory.

If no COMMAND is specified, shell is started with a timeout of 10 minutes.
EOF
    ) 1>&2
    exit 0
fi

. /etc/ramroot/boot-info
export ramroot="$(mktemp -d)"
if ! mount -o ro -U "$boot_uuid" "$ramroot"; then
    echo "Unable to mount ramroot snapshot filesystem"
    exit 1
fi
if [ "$1" = "" ]; then
    echo "Mounted ramroot read-only at $ramroot (\$ramroot)"
    echo "Spawning shell with 10-minute timeout for umount"
    TMOUT=600 /bin/bash
else
    "$@"
fi
umount "$ramroot"
