#!/bin/sh

usage() {
cat 1>&2 <<EOF
usage: ramroot snapshot create DESCRIPTION
       ramroot snapshot delete ID
       ramroot snapshot compress ID
       ramroot snapshot list
       ramroot snapshot resize
       ramroot snapshot enable [ID|latest] [fallback [FALLBACK-ID|current] [FALLBACK-TIMEOUT]]
       ramroot watchdog start TIMEOUT
       ramroot watchdog [stop|refresh|status]
       ramroot admin [CMD]
       ramroot upgrade [VERSION]

snapshot create: Create a snapshot of the running system.

snapshot enable: Configure boot loader to boot snapshot ID on next
boot.  If FALLBACK-ID is specified a watchdog will boot snapshot
FALLBACK-ID if watchdog is not stopped within FALLBACK-TIMEOUT
seconds. Timeout defaults to 10 minutes.

admin: Run a command in an environment where \$ramroot points to the
snapshot directory. If no command is specified a shell is started with
a timeout of 10 minutes.

upgrade: Upgrade ramroot tools from git. VERSION defaults to "master".
EOF
exit 0
}

fatal() {
    echo "$@" 1>&2
    exit 1
}

build_grubenv() {
    (
	echo "# GRUB Environment Block"
	cat
	for i in $(seq 1 1024); do
	    echo -n "#"
	done
    ) | dd bs=1 count=1024 2> /dev/null
}

ramroot_mount_ro() {
    if [ "$ramroot_build" != "1" ]; then
        ramroot="$(mktemp -d)"
        if ! mount -o ro -U "$boot_uuid" "$ramroot"; then
            fatal "Unable to mount ramroot snapshot filesystem"
        fi
    fi
}

ramroot_mount_rw() {
    if [ "$ramroot_build" != "1" ]; then
        if ! mount -o remount,rw "$ramroot"; then
            ramroot_umount
            fatal "Unable to mount ramroot snapshot filesystem for read-write use"
        fi
    fi
}

ramroot_umount() {
    if [ "$ramroot_build" != "1" ]; then
        if ! umount "$ramroot"; then
            fatal "Unable to unmount ramroot snapshot filesystem"
        fi
    fi
}

snapshot_create() {
    local desc="$1"
    local flags="$2"
    
    local prev="$boot_snapshot"

    ramroot_mount_ro
    if [ ! -d "$ramroot/snapshot/$prev" ]; then
        ramroot_umount
        fatal "Old snapshot $prev does not exist"
    fi
    local new="$prev"
    while [ -d "$ramroot/snapshot/$new" ]; do
        new="$(expr $new + 1)"
    done
    local available_space="$(df --block-size=1 --output=avail "$ramroot" | tail -n1)"
    local required_space="$(du --one-file-system --summarize --bytes / | cut -f1)"
    if [ "$available_space" -lt "$required_space" ]; then
        ramroot_umount
        fatal "Not enough space for a new snapshot. Consider running \"ramroot snapshot resize\" to resize the snapshot filesystem to use the whole disk or delete some snapshots."
    fi
    echo "#$new $(date -u +"%Y-%m-%d %H:%M") $desc" > /etc/ramroot/grub-title
    echo $required_space > /etc/ramroot/size
    ramroot_mount_rw
    local partial="$ramroot/snapshot_partial"
    local final="$ramroot/snapshot/$new"
    if [ -e "$partial" ]; then
        rm -fr "$partial"
    fi
    rsync --numeric-ids --acls --xattrs -ax --delete "--link-dest=../snapshot/$prev" --exclude "$ramroot" / "$partial"
    local rc="$?"
    if [ "$rc" = "0" -o "$rc" = "24" ]; then
        mv "$partial" "$final"
        ramroot_umount
        echo "Created snapshot $new"
    else
        rm -fr "$partial"
        ramroot_umount
        fatal "rsync failed with code $rc"
    fi
}

snapshot_delete() {
    local id="$1"
    if [ "$id" = "$boot_snapshot" ]; then
        fatal "Cannot delete running snapshot"
    fi
    ramroot_mount_ro
    if [ ! -d "$ramroot/snapshot/$id" ]; then
        ramroot_umount
        fatal "Snapshot $id does not exist"
    fi
    ramroot_mount_rw
    rm -f "$ramroot/snapshot/$id.tar.zst"
    local partial="$ramroot/snapshot_partial"
    if [ -e "$partial" ]; then
        rm -fr "$partial"
    fi
    mv "$ramroot/snapshot/$id" "$partial"
    rm -fr "$partial"
    ramroot_umount
}

snapshot_compress() {
    local id="$1"

    if [ "$id" = "latest" ]; then
        id="$(cd "$ramroot/snapshot" && find * -maxdepth 0 -type d | sort -n | tail -n1)"
    fi

    ramroot_mount_ro
    if [ ! -d "$ramroot/snapshot/$id" ]; then
        ramroot_umount
        fatal "Snapshot $id does not exist"
    fi
    ramroot_mount_rw
    tar -c --numeric-owner --selinux --acls --xattrs --xattrs-include=security.* --zstd -C "$ramroot/snapshot/$id" -f "$ramroot/snapshot/$id.tar.zst.partial" . && mv "$ramroot/snapshot/$id.tar.zst.partial" "$ramroot/snapshot/$id.tar.zst"
    ramroot_umount
}

snapshot_list() {
    ramroot_mount_ro
    . "$ramroot/boot/grub/grub.cfg.info"
    echo "# Free space:$(df --output=avail -h "$ramroot" | tail -n1)"
    for i in $(cd "$ramroot/snapshot" && find * -maxdepth 0 -type d | sort -n); do
        local size="$(expr $(cat "$ramroot/snapshot/$i/etc/ramroot/size") / 1000000)"
        echo "$i (${size}MB) $(cat "$ramroot/snapshot/$i/etc/ramroot/grub-title")"
        if [ "$i" = "$boot_snapshot" ]; then
            echo "- running snapshot"
            echo "  - booted on $(date -Is -d @$(expr $(date +%s) - $(cat /proc/uptime |cut -d. -f1)))"
            echo "  - uptime $(uptime --pretty|cut -d' ' -f2-)"
        fi
        if [ "$i" = "$default" ]; then
            echo "- default snapshot"
        fi
        if [ "$i" = "$fallback" ]; then
            echo "- fallback snapshot"
            echo "  - fallback timeout $fallback_timeout"
        fi
        if [ -e "$ramroot/snapshot/$i.tar.zst" ]; then
            local compressed_size_bytes="$(du --one-file-system --summarize --bytes "$ramroot/snapshot/$i.tar.zst" | cut -f1)"
            local compressed_size="$(expr $compressed_size_bytes / 1000000)"
            echo "- compressed to ${compressed_size}MB"
        fi

    done
    ramroot_umount
}

snapshot_resize() {
    local filesystem_blockdev="$(readlink -f "/dev/disk/by-uuid/$boot_uuid")"
    local blockdev="$(echo "$filesystem_blockdev" | sed 's@[0-9]*$@@')"

    part_begin="$(fdisk "$blockdev" -l -o start,device | grep "$filesystem_blockdev$" | awk '{print $1}')"

    fsck -p -f "$filesystem_blockdev"
    /sbin/fdisk -C 61 -H 255 -S 63 -c -u "$blockdev" <<EOF
d
n
p
1
$part_begin

n
w
EOF
    resize2fs "$filesystem_blockdev"
    local rc="$?"
    if [ "$rc" != "0" ]; then
        fatal "resize2fs failed with code $rc"
    fi
}


snapshot_enable() {
    local default="$1"
    local fallback="$2"
    local fallback_timeout="$3"

    ramroot_mount_ro

    if [ "$default" = "latest" ]; then
        default="$(cd "$ramroot/snapshot" && find * -maxdepth 0 -type d | sort -n | tail -n1)"
    fi

    if [ ! -d "$ramroot/snapshot/$default/boot" ]; then
        ramroot_umount
        fatal "Default snapshot does not exist"
    fi

    if [ "$fallback" != "" ]; then
        if [ "$fallback" = "current" ]; then
            fallback="$boot_snapshot"
        fi

        if [ ! -d "$ramroot/snapshot/$fallback/boot" ]; then
            ramroot_umount
            fatal "Fallback snapshot does not exist"
        fi
    fi
    if [ "$fallback_timeout" = "" ]; then
        fallback_timeout=600
    fi

    local entries="$(mktemp)"
    local idx=0
    for i in $(cd "$ramroot/snapshot" && find * -maxdepth 0 -type d | sort -n); do
        if [ "$i" = "$default" ]; then
	    local default_idx=$idx
        fi
        if [ "$i" = "$fallback" ]; then
	    local fallback_idx=$idx
        fi
        title="$(cat "$ramroot/snapshot/$i/etc/ramroot/grub-title")"
        extraopts=" ramroot_uuid=$boot_uuid ramroot_snapshot=$i"
        extraopts="$extraopts $(cat "$ramroot/snapshot/$i/etc/ramroot/grub-extraopts")"
        if [ "$fallback" != "" -a "$i" = "$default" ]; then
	    extraopts="$extraopts ramroot_watchdog=$fallback_timeout"
        fi
        cat >> $entries <<EOF
menuentry '$title' --class debian --class gnu-linux --class gnu --class os {
EOF
        if [ "$fallback" != "" -a "$i" = "$default" ]; then
	    echo " set savedefault=$fallback_idx" >> $entries
	    echo " save_env savedefault" >> $entries
        fi
        cat >> "$entries" <<EOF
 insmod part_msdos
 insmod ext2
 set root='(hd0,msdos1)'
 search --no-floppy --fs-uuid --set $boot_uuid
 echo 'Loading $title'
 linux /snapshot/$i/vmlinuz $extraopts
 echo 'Loading initial ramdisk ...'
 initrd /snapshot/$i/initrd.img
 echo 'Now booting the kernel ...'
}
EOF
        echo >> "$entries"
        idx="$(expr $idx + 1)"
    done

    local grubcfg="$(mktemp)"
    echo "set timeout=10" >> "$grubcfg"
    echo "set root='(hd0,msdos1)'" >> "$grubcfg"
    if [ "$fallback" != "" ]; then
        echo "load_env" >> $grubcfg
        echo "set default=\${savedefault}" >> "$grubcfg"
    else
        echo "set default=\"$default_idx\"" >> "$grubcfg"
    fi
    echo >> "$grubcfg"
    cat "$entries" >> "$grubcfg"
    rm "$entries"

    if ! grep initrd "$grubcfg" > /dev/null; then
        ramroot_umount
        fatal incomplete grub.cfg
    fi

    ramroot_mount_rw
    mv "$grubcfg" "$ramroot/boot/grub/grub.cfg"
    local grubcfginfo="$(mktemp)"
    echo default=$default >> "$grubcfginfo"
    if [ "$fallback" != "" ]; then
        echo fallback=$fallback >> "$grubcfginfo"
        echo fallback_timeout=$fallback_timeout >> "$grubcfginfo"
    fi
    mv "$grubcfginfo" "$ramroot/boot/grub/grub.cfg.info"
    if [ "$fallback" != "" ]; then
        echo "savedefault=$default_idx" | build_grubenv > "$ramroot/boot/grub/grubenv"
    else
        echo -n "" | build_grubenv > "$ramroot/boot/grub/grubenv"
    fi
    ramroot_umount
}

watchdog_start() {
    local timeout="$1"
    if [ ! -e /dev/watchdog ]; then
        mknod /dev/watchdog c 10 130
    fi
    if [ -e /sys/module/softdog ]; then
        rmmod softdog
    fi
    modprobe softdog "soft_margin=$timeout"
    watchdog_refresh
}

watchdog_stop() {
    echo -n V > /dev/watchdog
}

watchdog_refresh() {
    echo -n S > /dev/watchdog
}

watchdog_status() {
    if [ "$(lsmod | grep ^softdog | awk '{print $3}')" = "1" ]; then
        echo running
    else
        echo stopped
    fi
}

admin() {
    ramroot_mount_ro
    export ramroot
    if [ "$1" = "" ]; then
        echo "Mounted ramroot read-only at $ramroot (\$ramroot)"
        echo "Spawning shell with 10-minute timeout for umount"
        TMOUT=600 /bin/bash
    else
        "$@"
    fi
    ramroot_umount
}

download_from_git() {
    local relative_url="$1"
    local local_filename="$2"
    local version="$3"

    local url="https://raw.githubusercontent.com/lindi2/ramroot/$version/$relative_url"
    local tmp_local_filename="$(mktemp)"
    busybox wget -q -O "$tmp_local_filename" "$url"
    if [ $? -ne 0 ]; then
        rm -f "$tmp_local_filename"
        fatal "Downloading $local_filename failed"
    fi
    diff -u "$local_filename" "$tmp_local_filename"
    if [ $? -eq 0 ]; then
        echo "$local_filename is already up-to-date"
        return
    fi
    read -p "Accept patch for $local_filename? [y/N] " ok
    if [ "$ok" = "y" ]; then
        echo "Patching $local_filename"
        mv "$tmp_local_filename" "$local_filename"
    else
        rm -f "$tmp_local_filename"
    fi
}

upgrade() {
    local version="$1"
    if [ "$version" = "" ]; then
        version="master"
    fi
    download_from_git scripts/ramroot /usr/local/bin/ramroot "$version"
    download_from_git scripts/ramroot-profile.sh /etc/profile.d/ramroot-profile.sh "$version"
    download_from_git scripts/modules /etc/initramfs-tools/modules "$version"
    download_from_git scripts/local-top /etc/initramfs-tools/scripts/local-top/ramroot "$version"
    download_from_git scripts/local-premount /etc/initramfs-tools/scripts/local-premount/ramroot "$version"
    download_from_git scripts/hooks /etc/initramfs-tools/hooks/ramroot "$version"

    update-initramfs -k $(uname -r) -d
    update-initramfs -k $(uname -r) -c
}

if [ "$ramroot_build" != "1" ]; then
    . /etc/ramroot/boot-info
fi

if [ "$(whoami)" != "root" ]; then
   echo "Sorry, you need to be root to run this tool"
   exit 1
fi

case "$1" in
    snapshot)
        case "$2" in
            create)
                snapshot_create "$3"
                ;;
            delete)
                snapshot_delete "$3"
                ;;
            compress)
                snapshot_compress "$3"
                ;;
            enable)
                case "$4" in
                    fallback)
                        snapshot_enable "$3" "$5" "$6"
                        ;;
                    "")
                        snapshot_enable "$3"
                        ;;
                    *)
                        usage
                        ;;
                esac
                ;;
            list)
                snapshot_list
                ;;
            resize)
                snapshot_resize
                ;;
            *)
                usage
                ;;
        esac
        ;;
    watchdog)
        case "$2" in
            start)
                watchdog_start "$3"
                ;;
            stop)
                watchdog_stop
                ;;
            refresh)
                watchdog_refresh
                ;;
            status)
                watchdog_status
                ;;
            *)
                usage
                ;;
        esac
        ;;
    admin)
        shift
        admin "$@"
        ;;
    upgrade)
        upgrade "$2"
        ;;
    *)
        usage
        ;;
esac
