#!/bin/sh
. /etc/ramroot/boot-info
export ramroot="$(mktemp -d)"
mount -o ro -U "${boot_uuid}" $ramroot
if [ "$1" = "" ]; then
    echo "Mounted ramroot read-only at $ramroot (\$ramroot)"
    echo "Spawning shell with 10-minute timeout for umount"
    TMOUT=600 /bin/bash
else
    "$@"
fi
umount $ramroot
