#!/bin/sh
if [ "$ramroot" = "" ]; then
    echo "Use only with ramroot-admin"
    exit 1
fi

default="$1"
fallback="$2"
fallback_timeout="$3"

if [ ! -d "$ramroot/snapshot/${default}/boot" ]; then
    echo "Default snapshot does not exist"
    exit 1
fi

newlst=`mktemp`

echo "timeout 10" >> $newlst
echo "root (hd0,0)" >> $newlst
if [ "$fallback" != "" ]; then
    echo "default saved" >> $newlst
    echo "fallback $fallback" >> $newlst
else
    echo "default $default" >> $newlst
fi

if [ -e /etc/ramroot/boot-info ]; then
    . /etc/ramroot/boot-info
fi
for i in `cd $ramroot/snapshot && echo *`; do
    title="`cat $ramroot/snapshot/$i/etc/ramroot/grub-title`"
    echo "title $title" >> $newlst
    grep -E "^(kernel|initrd)" $ramroot/snapshot/$i/boot/grub/menu.lst\
    | head -n 2\
    | sed "s@^@ @;s@/boot/@/snapshot/$i/boot/@;s@ root=/dev/hda1 ro @ @"\
    | sed "/^ kernel/s@\$@ ramroot_uuid=$boot_uuid ramroot_snapshot=$i@"\
    >> $newlst
    echo >> $newlst
done

mount -o remount,rw $ramroot
mv $newlst $ramroot/boot/grub/menu.lst
mount -o remount,ro $ramroot
