#!/bin/sh
case "$1" in
    start)
	mount -t tmpfs none /var/cache/apt
	mkdir -p /var/cache/apt/archives/partial
	;;
    stop)
	umount /var/cache/apt
	;;
    *)
	echo "usage: $0 [stop|start]" 1>&2
	exit 1
	;;
esac
